### PR TITLE
vectorization

### PR DESCRIPTION
**Pull request by halvarsu**
Vectorizing some functions for a speed up of 50x-300x.

### CODE REVIEW

**Comment by lepmik** [comment]
nice, but please make sure functions keep their intended function :)

**Comment by halvarsu** [comment]
Oh, I see, added a new commit now. I guess it is ok to convert to numpy array (as the old function did it already)?

**Comment by halvarsu** [comment]
Uhm... I can't see how these failures are my fault. At least the failures of aa040d836767825ffba6928e0f4a97f14acbced6 in `exana/tests/test_tracking.py` are gone :)

**Comment by lepmik** [comment]
if you look at the Travis report there is some tests which are failing due to bad formatting, not sure why this has happened, but might be some numpy version change in __repr__ or __string__, The easiest fix is to edit the formatting of the output as there is no quantitative errors.

**Comment by halvarsu** [comment]
Yep, looks like there are some major changes in printing in [numpy version 1.14](https://docs.scipy.org/doc/numpy-1.14.0/release.html).

**Comment by lepmik** [comment]
ready to merge?

**Pull request merged**
