### PR TITLE
Recognizing and analysing grid fields

### PR DESCRIPTION
**Pull request by halvarsu**

### CODE REVIEW

**Comment by lepmik** [comment]
Any updates to this pull request will be very appreciated. To resolve conflicting files follow these steps
```
git remote add upstream https://github.com/CINPLA/exana.git
git branch backup dev
git checkout dev
git reset --hard upstream/dev
git cherry-pick 64174e0a81525d9033ab2dd9c5bd1370737ffa9f c81e3f95646d768b35cff67f26d4beb14e42096f 44179b96803091627625099a0a055fd54b6b9012 22c0938cd9e2ea17cfef5564661467c343a084bb 3e7edf835d1aad0253da81e018f0936d007876bd eb85c7ae94b56496a9054bca64665db3d4249773
```
Make sure your log is good
```
git push --force
```

Then you have to add imports [here](https://github.com/halvarsu/exana/blob/eb85c7ae94b56496a9054bca64665db3d4249773/exana/tracking/__init__.py#L1)

Then run `py.test` in your root structure and resolve test issues.

**Comment by halvarsu** [comment]
Sure! To include the latest changes, I will also include the following commits from origin/separate_fields:

1b3d09727624359a8b82ca1fc322a482d9d2a65b
fdd0c576a63418df22f962729821d97f42d74b4e
76154c5dbf76fb02f03aa3884ac52fdb5a545c2f
fb9f3fe38e8ae501e5119b1287d87884bfe438a5
7625ff4d20575ef89bd9506a3db4dc9a1f847b13
11965d6e8600d781132cabcd493565da64606541
5f78c0abe5966ea5d800374e796803e0a89e2e62

**Comment by lepmik** [comment]
Great, If you can also sort out the failing tests that would be great! thank you

**Comment by halvarsu** [comment]
Should be working now

EDIT: Or not. Will look into this

**Pull request merged**
